// ─────────────────────────────────────────────────────────────────────────────
// AUTONORME — Codes d'erreur métier standardisés
// Format : AUTONORME_[DOMAINE]_[CODE]
// Source de vérité unique — utilisé par backend ET frontend
// ─────────────────────────────────────────────────────────────────────────────

export const ErrorCodes = {
  // AUTH
  AUTH_OTP_INVALID: 'AUTONORME_AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTONORME_AUTH_OTP_EXPIRED',
  AUTH_TOKEN_EXPIRED: 'AUTONORME_AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTONORME_AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTONORME_AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTONORME_AUTH_FORBIDDEN',

  // VEHICLE
  VEHICLE_NOT_FOUND: 'AUTONORME_VEHICLE_NOT_FOUND',
  VEHICLE_VIN_INVALID: 'AUTONORME_VEHICLE_VIN_INVALID',
  VEHICLE_ALREADY_EXISTS: 'AUTONORME_VEHICLE_ALREADY_EXISTS',

  // GARAGE
  GARAGE_NOT_FOUND: 'AUTONORME_GARAGE_NOT_FOUND',
  GARAGE_UNAVAILABLE: 'AUTONORME_GARAGE_UNAVAILABLE',
  GARAGE_SLOT_TAKEN: 'AUTONORME_GARAGE_SLOT_TAKEN',

  // APPOINTMENT
  APPOINTMENT_NOT_FOUND: 'AUTONORME_APPOINTMENT_NOT_FOUND',
  APPOINTMENT_CANNOT_CANCEL: 'AUTONORME_APPOINTMENT_CANNOT_CANCEL',

  // PART
  PART_NOT_FOUND: 'AUTONORME_PART_NOT_FOUND',
  PART_INCOMPATIBLE: 'AUTONORME_PART_INCOMPATIBLE',
  PART_OUT_OF_STOCK: 'AUTONORME_PART_OUT_OF_STOCK',
  PART_IMPORT_ONLY: 'AUTONORME_PART_IMPORT_ONLY',

  // ORDER
  ORDER_NOT_FOUND: 'AUTONORME_ORDER_NOT_FOUND',
  ORDER_PAYMENT_FAILED: 'AUTONORME_ORDER_PAYMENT_FAILED',
  ORDER_CANNOT_CANCEL: 'AUTONORME_ORDER_CANNOT_CANCEL',

  // AUTOBOT
  AUTOBOT_CONTEXT_MISSING: 'AUTONORME_AUTOBOT_CONTEXT_MISSING',
  AUTOBOT_RATE_LIMIT: 'AUTONORME_AUTOBOT_RATE_LIMIT',
  AUTOBOT_ESCALATION_REQUIRED: 'AUTONORME_AUTOBOT_ESCALATION_REQUIRED',

  // WHATSAPP
  WHATSAPP_SEND_FAILED: 'AUTONORME_WHATSAPP_SEND_FAILED',
  WHATSAPP_SIGNATURE_INVALID: 'AUTONORME_WHATSAPP_SIGNATURE_INVALID',

  // GENERIC
  VALIDATION_ERROR: 'AUTONORME_VALIDATION_ERROR',
  NOT_FOUND: 'AUTONORME_NOT_FOUND',
  INTERNAL_ERROR: 'AUTONORME_INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'AUTONORME_RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

// Format de réponse d'erreur standardisé
export interface ApiError {
  success: false;
  error: {
    code: ErrorCode;
    message: string;
    details?: Record<string, unknown>;
    timestamp: string;
  };
}

// Format de réponse succès standardisé
export interface ApiSuccess<T> {
  success: true;
  data: T;
  meta?: {
    page?: number;
    limit?: number;
    total?: number;
  };
}

export type ApiResponse<T> = ApiSuccess<T> | ApiError;
